---
- name: install HTTP server
  hosts: g1
  become: yes


  tasks:
  - name: install HTTPD
    yum:
      name: httpd
      state: present
    when: ansible_distribution == "Amazon"

  - name: start httpd
    service:
      name: httpd
      state: started
    when: ansible_distribution == "Amazon"

  - name: enable httpd
    service:
      name: httpd
      state: yes
    when: ansible_distribution == "Amazon"
   
  - name: install Apache2
    apt:
      name: Apache2
      state: present
    when: ansible_distribution == "Ubuntu"
      

  - name: start Apache2
    service:
      name: Apache2
      state: started
    when: ansible_distribution == "Ubuntu"

  - name: enable apache2
    service:
      name: apache2
      state: yes  
    when: ansible_distribution == "Ubuntu"             
...

