---
- name: install HTTP server
  hosts: g1
  become: yes


  tasks:
  - name: install Apache2
    apt:
      name: Apache2
      state: present

  - name: start Apache2
    service:
      name: Apache2
      state: started

  - name: enable apache2
    service:
      name: apache2
      state: yes     
...

