---
- name: custom variable
  hosts: g1
  become: yes
  vars:
    myusername: 200anthony


  tasks:
  - name: update Dynamic page
    template:
      src: template.j2
      dest: /var/www/html/template.html
         
...
