---
- name: custom variable
  hosts: g1
  become: yes
  vars:
    myusername: suoton


  tasks:
  - name: update Dynamic page
    template:
      src: Dynamic-template.j2
      dest: /var/www/html/Dynamic-template.html
         
...
